-- Run this once in the SQL Editor of EVERY Supabase project you want to keep alive.

create table if not exists "keep-alive" (
  id          bigint generated by default as identity primary key,
  name        text default '',
  random      uuid default gen_random_uuid(),
  inserted_at timestamptz default now()
);

-- Seed one row so reads always have something to look at.
insert into "keep-alive" (name) values ('keep-alive');

-- --------------------------------------------------------------------------
-- ONLY needed if you ping with the anon key instead of the service_role key.
-- The service_role key bypasses RLS, so you can skip this block when using it.
-- --------------------------------------------------------------------------
-- alter table "keep-alive" enable row level security;
-- create policy "keep-alive anon read" on "keep-alive"
--   for select to anon using (true);
